package com.zenixia.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.model.EquipmentType;
import com.zenixia.plugins.service.EquipmentTypeLocalServiceUtil;

/**
 * The extended model base implementation for the EquipmentType service. Represents a row in the &quot;RoomBooking_EquipmentType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EquipmentTypeImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see EquipmentTypeImpl
 * @see com.zenixia.plugins.model.EquipmentType
 * @generated
 */
public abstract class EquipmentTypeBaseImpl extends EquipmentTypeModelImpl
    implements EquipmentType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a equipment type model instance should use the {@link EquipmentType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EquipmentTypeLocalServiceUtil.addEquipmentType(this);
        } else {
            EquipmentTypeLocalServiceUtil.updateEquipmentType(this);
        }
    }
}
