package com.zenixia.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.model.Equipment;
import com.zenixia.plugins.service.EquipmentLocalServiceUtil;

/**
 * The extended model base implementation for the Equipment service. Represents a row in the &quot;RoomBooking_Equipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EquipmentImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see EquipmentImpl
 * @see com.zenixia.plugins.model.Equipment
 * @generated
 */
public abstract class EquipmentBaseImpl extends EquipmentModelImpl
    implements Equipment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a equipment model instance should use the {@link Equipment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            EquipmentLocalServiceUtil.addEquipment(this);
        } else {
            EquipmentLocalServiceUtil.updateEquipment(this);
        }
    }
}
