package com.zenixia.plugins.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.zenixia.plugins.model.RoomBooking;
import com.zenixia.plugins.service.RoomBookingLocalServiceUtil;

/**
 * The extended model base implementation for the RoomBooking service. Represents a row in the &quot;RoomBooking_RoomBooking&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoomBookingImpl}.
 * </p>
 *
 * @author Guillaume Lenoir
 * @see RoomBookingImpl
 * @see com.zenixia.plugins.model.RoomBooking
 * @generated
 */
public abstract class RoomBookingBaseImpl extends RoomBookingModelImpl
    implements RoomBooking {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a room booking model instance should use the {@link RoomBooking} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RoomBookingLocalServiceUtil.addRoomBooking(this);
        } else {
            RoomBookingLocalServiceUtil.updateRoomBooking(this);
        }
    }
}
