package com.glenoir.plugins.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the EquipmentType service. Represents a row in the &quot;RoomBooking_EquipmentType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.glenoir.plugins.model.impl.EquipmentTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.glenoir.plugins.model.impl.EquipmentTypeImpl}.
 * </p>
 *
 * @author guillaume Lenoir
 * @see EquipmentType
 * @see com.glenoir.plugins.model.impl.EquipmentTypeImpl
 * @see com.glenoir.plugins.model.impl.EquipmentTypeModelImpl
 * @generated
 */
public interface EquipmentTypeModel extends BaseModel<EquipmentType>,
    StagedAuditedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a equipment type model instance should use the {@link EquipmentType} interface instead.
     */

    /**
     * Returns the primary key of this equipment type.
     *
     * @return the primary key of this equipment type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this equipment type.
     *
     * @param primaryKey the primary key of this equipment type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this equipment type.
     *
     * @return the uuid of this equipment type
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this equipment type.
     *
     * @param uuid the uuid of this equipment type
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the equipment type ID of this equipment type.
     *
     * @return the equipment type ID of this equipment type
     */
    public long getEquipmentTypeId();

    /**
     * Sets the equipment type ID of this equipment type.
     *
     * @param equipmentTypeId the equipment type ID of this equipment type
     */
    public void setEquipmentTypeId(long equipmentTypeId);

    /**
     * Returns the company ID of this equipment type.
     *
     * @return the company ID of this equipment type
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this equipment type.
     *
     * @param companyId the company ID of this equipment type
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this equipment type.
     *
     * @return the user ID of this equipment type
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this equipment type.
     *
     * @param userId the user ID of this equipment type
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this equipment type.
     *
     * @return the user uuid of this equipment type
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this equipment type.
     *
     * @param userUuid the user uuid of this equipment type
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this equipment type.
     *
     * @return the user name of this equipment type
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this equipment type.
     *
     * @param userName the user name of this equipment type
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this equipment type.
     *
     * @return the create date of this equipment type
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this equipment type.
     *
     * @param createDate the create date of this equipment type
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this equipment type.
     *
     * @return the modified date of this equipment type
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this equipment type.
     *
     * @param modifiedDate the modified date of this equipment type
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this equipment type.
     *
     * @return the name of this equipment type
     */
    public String getName();

    /**
     * Returns the localized name of this equipment type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this equipment type
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this equipment type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this equipment type. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this equipment type in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this equipment type
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this equipment type in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this equipment type
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this equipment type.
     *
     * @return the locales and localized names of this equipment type
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this equipment type.
     *
     * @param name the name of this equipment type
     */
    public void setName(String name);

    /**
     * Sets the localized name of this equipment type in the language.
     *
     * @param name the localized name of this equipment type
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this equipment type in the language, and sets the default locale.
     *
     * @param name the localized name of this equipment type
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this equipment type from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this equipment type
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this equipment type from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this equipment type
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public String[] getAvailableLanguageIds();

    public String getDefaultLanguageId();

    public void prepareLocalizedFieldsForImport() throws LocaleException;

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    @Override
    public Object clone();

    @Override
    public int compareTo(EquipmentType equipmentType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<EquipmentType> toCacheModel();

    @Override
    public EquipmentType toEscapedModel();

    @Override
    public EquipmentType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
