package com.glenoir.plugins.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Room service. Represents a row in the &quot;RoomBooking_Room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.glenoir.plugins.model.impl.RoomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.glenoir.plugins.model.impl.RoomImpl}.
 * </p>
 *
 * @author guillaume Lenoir
 * @see Room
 * @see com.glenoir.plugins.model.impl.RoomImpl
 * @see com.glenoir.plugins.model.impl.RoomModelImpl
 * @generated
 */
public interface RoomModel extends BaseModel<Room>, StagedAuditedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a room model instance should use the {@link Room} interface instead.
     */

    /**
     * Returns the primary key of this room.
     *
     * @return the primary key of this room
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this room.
     *
     * @param primaryKey the primary key of this room
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this room.
     *
     * @return the uuid of this room
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this room.
     *
     * @param uuid the uuid of this room
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the room ID of this room.
     *
     * @return the room ID of this room
     */
    public long getRoomId();

    /**
     * Sets the room ID of this room.
     *
     * @param roomId the room ID of this room
     */
    public void setRoomId(long roomId);

    /**
     * Returns the company ID of this room.
     *
     * @return the company ID of this room
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this room.
     *
     * @param companyId the company ID of this room
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this room.
     *
     * @return the user ID of this room
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this room.
     *
     * @param userId the user ID of this room
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this room.
     *
     * @return the user uuid of this room
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this room.
     *
     * @param userUuid the user uuid of this room
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this room.
     *
     * @return the user name of this room
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this room.
     *
     * @param userName the user name of this room
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this room.
     *
     * @return the create date of this room
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this room.
     *
     * @param createDate the create date of this room
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this room.
     *
     * @return the modified date of this room
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this room.
     *
     * @param modifiedDate the modified date of this room
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the name of this room.
     *
     * @return the name of this room
     */
    public String getName();

    /**
     * Returns the localized name of this room in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this room
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this room in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this room. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this room in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this room
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this room in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this room
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this room.
     *
     * @return the locales and localized names of this room
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this room.
     *
     * @param name the name of this room
     */
    public void setName(String name);

    /**
     * Sets the localized name of this room in the language.
     *
     * @param name the localized name of this room
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this room in the language, and sets the default locale.
     *
     * @param name the localized name of this room
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this room from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this room
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this room from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this room
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    /**
     * Returns the description of this room.
     *
     * @return the description of this room
     */
    public String getDescription();

    /**
     * Returns the localized description of this room in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized description of this room
     */
    @AutoEscape
    public String getDescription(Locale locale);

    /**
     * Returns the localized description of this room in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this room. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getDescription(Locale locale, boolean useDefault);

    /**
     * Returns the localized description of this room in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized description of this room
     */
    @AutoEscape
    public String getDescription(String languageId);

    /**
     * Returns the localized description of this room in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this room
     */
    @AutoEscape
    public String getDescription(String languageId, boolean useDefault);

    @AutoEscape
    public String getDescriptionCurrentLanguageId();

    @AutoEscape
    public String getDescriptionCurrentValue();

    /**
     * Returns a map of the locales and localized descriptions of this room.
     *
     * @return the locales and localized descriptions of this room
     */
    public Map<Locale, String> getDescriptionMap();

    /**
     * Sets the description of this room.
     *
     * @param description the description of this room
     */
    public void setDescription(String description);

    /**
     * Sets the localized description of this room in the language.
     *
     * @param description the localized description of this room
     * @param locale the locale of the language
     */
    public void setDescription(String description, Locale locale);

    /**
     * Sets the localized description of this room in the language, and sets the default locale.
     *
     * @param description the localized description of this room
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setDescription(String description, Locale locale,
        Locale defaultLocale);

    public void setDescriptionCurrentLanguageId(String languageId);

    /**
     * Sets the localized descriptions of this room from the map of locales and localized descriptions.
     *
     * @param descriptionMap the locales and localized descriptions of this room
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap);

    /**
     * Sets the localized descriptions of this room from the map of locales and localized descriptions, and sets the default locale.
     *
     * @param descriptionMap the locales and localized descriptions of this room
     * @param defaultLocale the default locale
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap,
        Locale defaultLocale);

    /**
     * Returns the capacity of this room.
     *
     * @return the capacity of this room
     */
    public int getCapacity();

    /**
     * Sets the capacity of this room.
     *
     * @param capacity the capacity of this room
     */
    public void setCapacity(int capacity);

    /**
     * Returns the level of this room.
     *
     * @return the level of this room
     */
    public int getLevel();

    /**
     * Sets the level of this room.
     *
     * @param level the level of this room
     */
    public void setLevel(int level);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public String[] getAvailableLanguageIds();

    public String getDefaultLanguageId();

    public void prepareLocalizedFieldsForImport() throws LocaleException;

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    @Override
    public Object clone();

    @Override
    public int compareTo(Room room);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Room> toCacheModel();

    @Override
    public Room toEscapedModel();

    @Override
    public Room toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
