package com.glenoir.plugins.model.impl;

import com.glenoir.plugins.model.Room;
import com.glenoir.plugins.service.RoomLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Room service. Represents a row in the &quot;RoomBooking_Room&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RoomImpl}.
 * </p>
 *
 * @author guillaume Lenoir
 * @see RoomImpl
 * @see com.glenoir.plugins.model.Room
 * @generated
 */
public abstract class RoomBaseImpl extends RoomModelImpl implements Room {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a room model instance should use the {@link Room} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            RoomLocalServiceUtil.addRoom(this);
        } else {
            RoomLocalServiceUtil.updateRoom(this);
        }
    }
}
